### ISSUE TITLE
[Feature] Make it possible to control automatic tracking at experiment-level

### ISSUE THREAD

**Issue by alhankeser** [VariateApp/variate-engine#8]
## Feature

As a product experimenter, I want to, by default, track all pageviews on experiments, except for some experiments where I wish to override this default behavior. 

## Ideal solution

Add an additional, optional, item to the config file called `pageview`. 

If this is not present or set to `default`, use default behavior as configured when Variate is initialized. 
If set to `manual`, then pageviews will be tracked manually for this experiment. (e.g. I sent a pageview event from the component when it appears in the viewport)

## Alternatives (optional)

A built-in mechanism that tracks whether a component has been viewed by a user (automated impression tracking of whether a targeted component variation is in the viewport). 

## Additional context (optional)

None.

**Comment by foxted** [comment]
@alhankeser I'd like to use a boolean for this instead of string values. Can we add a `pageview` field or maybe `manualPageview`/`triggerPageview` boolean?

**Comment by alhankeser** [comment]
Could do `manualPageview`

**Comment by foxted** [comment]
So `manualPageview` boolean field on the experiment config?
